version: '3'

services:
  api:
    container_name: "snippet-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - wii-network
    expose:
      - "${PORT}"

  db:
    container_name: snippet-db
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - wii-network

networks:
  wii-network:
    name: wii-network
    driver: bridge

volumes:
  pgdata: