
services:
  server:
    container_name: "snippet-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SNIPPET_PORT}:${SNIPPET_PORT}"
    env_file:
      - .env

  db:
    container_name: "snippet-db"
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  blob:
    external: false