
services:
  server:
    container_name: "snippet-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SNIPPET_PORT}:${SNIPPET_PORT}"
    env_file:
      - .env

  db:
    container_name: "snippet-db"
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: "asset-service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "${ASSET_PORT}:${ASSET_PORT}"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  pgdata:
  blob:
    external: false