@startuml
'https://plantuml.com/sequence-diagram

autonumber

UI -> Proxy

Proxy -> SnippetService
SnippetService -> PermissionService: Get all snippets id from user
SnippetService -> Redis: Publishes Lint/Formatting event
Redis -> SnippetService: Consumes Lint/Formatting event
SnippetService -> PrintScriptService: Executes linting/formatting
PrintScriptService -> SnippetService: Status
SnippetService -> UI: Code linted/formatted
@enduml