@startuml
'https://plantuml.com/sequence-diagram

autonumber

UI -> Proxy

Proxy -> SnippetService
SnippetService -> PermissionService: Get all snippets id from user
SnippetService -> Redis: Send suscription
Redis -> Redis: Executes linting/formatting
Redis -> SnippetService: Send publish (event)
@enduml