@startuml
'https://plantuml.com/sequence-diagram

autonumber

UI -> Proxy
Proxy -> SnippetService

SnippetService -> PermissionService: Checks has share perm
PermissionService -> SnippetService: Has share perm
SnippetService -> PermissionService: Snippet to share
SnippetService -> AssetService: Gets snippet
SnippetService -> AssetService: Assigns snippet to friend ID
@enduml