name: "Continuous Deployment"
on:
  push:
    branches:
      - main
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project and create JAR
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for dev
        id: docker_build_dev
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ing-sistemas/snippet-service:dev-latest

      - name: Build and push Docker image for production
        id: docker_build_prod
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ing-sistemas/snippet-service:prod-latest

      - name: Set up Prod SSH key
        uses: webfactory/ssh-agent@v0.5.4
        if: github.ref == 'refs/heads/main'
        with:
          ssh-private-key: ${{ secrets.PROD_KEY }}

      - name: Deploy to Prod VM
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_PROD }} \
          "cd ${{secrets.WORKDIR}} && \
          docker compose stop snippet-service && \
          docker compose rm -f snippet-service && \
          docker compose pull snippet-service && \
          docker compose up -d snippet-service"

      - name: Set up Dev SSH key
        uses: webfactory/ssh-agent@v0.5.4
        if: github.ref == 'refs/heads/dev'
        with:
          ssh-private-key: ${{ secrets.DEV_KEY  }}

      - name: Deploy to Dev VM
        if: github.ref == 'refs/heads/dev'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEV }} \
          "cd ${{secrets.WORKDIR}} && \
          docker compose stop snippet-service && \
          docker compose rm -f snippet-service && \
          docker compose pull snippet-service && \
          docker compose up -d snippet-service"